### PR TITLE
Revert OSD-5915

### PR DESCRIPTION
**Pull request by mrbarge**
This commit reverts the changes made by [OSD-5915](https://issues.redhat.com/browse/OSD-5915).

The RHOAM group permissions have been reworked into the existing `layered` groups in MCC commit 580 [0], so there is no requirement to have the webhook cater for these groups any more.

cc @jewzaam @lisa @dofinn

[0] https://github.com/openshift/managed-cluster-config/pull/580

### CODE REVIEW

**Comment by jewzaam** [comment]
There are not differences reported here or if I diff origin/master locally.. bit confused given the commits look like something should show up.

**Comment by mrbarge** [comment]
> There are not differences reported here or if I diff origin/master locally.. bit confused given the commits look like something should show up.

Yeah, this confused me too! I eventually discovered that #121, which was merged after #122, un-did all the changes that were made by #122 anyway - which is why there's no difference between the current master and this branch.
So this revert is just a bit of a formality to give context to the commit history, I guess, since the revert has already happened? :confused:

**Comment by lisa** [comment]
> > There are not differences reported here or if I diff origin/master locally.. bit confused given the commits look like something should show up.
> 
> Yeah, this confused me too! I eventually discovered that #121, which was merged after #122, un-did all the changes that were made by #122 anyway - which is why there's no difference between the current master and this branch.
> So this revert is just a bit of a formality to give context to the commit history, I guess, since the revert has already happened? 😕

I guess I fouled up the rebase even worse than I thought. Sorry :( Or maybe it was foresight?

**Comment by lisa** [comment]
/approve

did not see it wasn't already.

**Comment by lisa** [comment]
What on earth is going on with the bot??!

/lgtm
/approve
/assign @lisa

**Comment by lisa** [comment]
It looks like the bot isn't keen on merging this, even with the explicit /approve and whatnot, so I guess we'll close this...?

**Pull request closed without merging**
