### PR TITLE
Osd 6029 remove user groups identities

### PR DESCRIPTION
**Pull request by sedroche**
Jira: https://issues.redhat.com/browse/OSD-6029

With backplane we have removed the SRE IDP and the groups. This PR removes webhooks related to those resources.

### CODE REVIEW

**Comment by sedroche** [comment]
@lisa @NautiluX I am getting permissions errors when running make to update the selectorsyncset.
```bash
Trying to pull quay.io/app-sre/golang:1.14...
Error: Error initializing source docker://quay.io/app-sre/golang:1.14: Error reading manifest 1.14 in quay.io/app-sre/golang: unauthorized: access to the requested resource is not authorized
make: *** [Makefile:85: build/selectorsyncset.yaml] Error 125
```

Can you help?

**Comment by lisa** [comment]
/hold

for review. I will review this today. Thank you for the PR

**Comment by lisa** [comment]
> @lisa @NautiluX I am getting permissions errors when running `make` to update the selectorsyncset.
> 
> ```shell
> Trying to pull quay.io/app-sre/golang:1.14...
> Error: Error initializing source docker://quay.io/app-sre/golang:1.14: Error reading manifest 1.14 in quay.io/app-sre/golang: unauthorized: access to the requested resource is not authorized
> make: *** [Makefile:85: build/selectorsyncset.yaml] Error 125
> ```
> 
> Can you help? I think that is the pr check failure

I've addressed this on Slack.

**Comment by lisa** [comment]
@sedroche I love this PR! It's lovely to see code being deleted. As you know, we need the selectorsyncset updated. I made a PR https://github.com/sedroche/managed-cluster-validating-webhooks/pull/1 for that in case your golang container image issues persist. If you're able to get the thing built with the image on your own and updated into this branch, that other PR can be closed. This is quite wonderful to see.

**Comment by sedroche** [comment]
@lisa Outstanding. Thank you for your help! I have merged your PR and the checks looks good now.

**Pull request merged**
