### PR TITLE
OSD-5394: First pass at automating documentation.

### PR DESCRIPTION
**Pull request by lisa**
See the Jira card for more details about how this might be used.

Signed-off-by: Lisa Seelye <lisa@users.noreply.github.com>

### CODE REVIEW

**Comment by lisa** [comment]
Note to self: Add README.md note about the interface change.

**Comment by lisa** [comment]
Of course, another rebase issue. I'll fix it up shortly.

**Comment by lisa** [comment]
I think I've fixed the previous rebase issue.

**Review by robotmaxtron — APPROVED** [review]
/lgtm

**Pull request merged**
