### PR TITLE
freeze-window-validation-webhook-tmpl - OSD-3515

### PR DESCRIPTION
**Pull request by himanshudogra**

### CODE REVIEW

**Comment by jewzaam** [comment]
pr check failed because templates need generated, run `make` and commit the changes

**Comment by lisa** [comment]
/hold

Is there a webhook for this?

**Comment by himanshudogra** [comment]
@lisa Thank you for checking. We can expect the webhooks logic to be finalized in the next phase of the upgrade operator or so. Once the webhook will be available, I will open another PR including everything in one go.

**Comment by lisa** [comment]
@himanshudogra I'm going to close this since #78 has been merged. The repository now doesn't use YAML files like this. Once the hook is implemented (in Go), the generation of this will be taken care of. Refer to the README.md to get started writing the hook in Go. If you need help, let me know.

**Pull request closed without merging**
